version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashr-api
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: ./docker/Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/dash-api:ro
    env_file:
      - .env


    
 
