name: dashr-api CI workflows
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      
      - name: Copy repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: actions/login@v2
        with:
          username: {{{ secrets.DOCKER_HUB_USERNAME }}}
          password: {{{ secrets.DOCKER_HUB_ACCESS_TOKEN }}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint

      - name: Format code
        run: npm run format
      


      # - name: Run tests
      #   run: npm run test

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: depthshq/dashr-api:latest




# name: dashr-api CI workflows
# on: 
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   container-build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [12.x]
    
#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v2

#       # - name: Login to Docker Hub
#       #   uses: docker/login-action@v2
#       #   with:
#       #     username: {{{ secrets.DOCKER_HUB_USERNAME }}}
#       #     password: {{{ secrets.DOCKER_HUB_ACCESS_TOKEN }}}
      
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install npm dependencies
#         run: npm ci
      
#       - name: Lint code
#         run: npm run lint

#       - name: Format code
#         run: npm run format
      
#       # - name: Run tests
#       #   run: npm run test

